<a href="https://colab.research.google.com/github/NewbieZilani/MSc-Explainable-AI/blob/main/01_NumPy/Indexing_%26_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import pandas as pd
import os

In [3]:
from google.colab import files

uploaded = files.upload()

Saving weather_dataset_2025.csv to weather_dataset_2025.csv

In [5]:
os.listdir()

['.config', 'weather_dataset_2025.csv', 'sample_data']

In [10]:
df = pd.read_csv("weather_dataset_2025.csv")

df.head()

,Date,City,Temperature_C,Humidity_%,Wind_Speed_km_h,Precipitation_mm,Condition
0,2025-01-01,Riyadh,15.8,94,21.0,0.00,Cloudy
1,2025-01-01,Jeddah,31.5,54,25.3,3.71,Windy
2,2025-01-01,Dammam,30.4,33,8.6,3.14,Partly Cloudy
3,2025-01-01,Dubai,34.0,37,18.7,0.00,Foggy
4,2025-01-01,Doha,28.3,32,6.8,0.00,Rainy

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5475 entries, 0 to 5474
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              5475 non-null   object
 1   City              5475 non-null   object
 2   Temperature_C     5475 non-null   float64
 3   Humidity_%        5475 non-null   int64
 4   Wind_Speed_km_h   5475 non-null   float64
 5   Precipitation_mm  5475 non-null   float64
 6   Condition         5475 non-null   object
dtypes: float64(3), int64(1), object(3)
memory usage: 299.5+ KB

In [12]:
# seperate numeric columns
numeric_df = df.select_dtypes(include="number")

numeric_df.head()

   Temperature_C  Humidity_%  Wind_Speed_km_h  Precipitation_mm
0           15.8          94             21.0              0.00
1           31.5          54             25.3              3.71
2           30.4          33              8.6              3.14
3           34.0          37             18.7              0.00
4           28.3          32              6.8              0.00

In [15]:
# create numpy array
weather = numeric_df.to_numpy()

print(weather)

[[15.8  94.   21.    0.  ]
 [31.5  54.   25.3   3.71]
 [30.4  33.    8.6   3.14]
 ...
 [ 6.3  42.   23.7  10.68]
 [27.6  58.   12.5   3.23]
 [44.3  75.    4.6   0.  ]]

In [16]:
# extract the column
temperature = weather[:, 0]

humidity = weather[:, 1]

wind = weather[:, 2]

precipitation = weather[:, 3]

In [18]:
print(temperature[:5])

[15.8 31.5 30.4 34.  28.3]

In [21]:
print(weather.shape)
rows, columns = weather.shape

print("Rows :", rows)
print("Columns :", columns)
print(weather.size)

(5475, 4)
Rows : 5475
Columns : 4
21900

In [33]:
# Indexing & Slicing
print(weather[:5])
print(weather[0])
print(weather[3])

# specific element finding
print(weather[0,0])
print(weather[3,2])

# To get full column
temperature=weather[:,0]
print(temperature)
print(temperature.size)

wind = weather[:, 2]
print(wind)
print(wind.size)

[[15.8  94.   21.    0.  ]
 [31.5  54.   25.3   3.71]
 [30.4  33.    8.6   3.14]
 [34.   37.   18.7   0.  ]
 [28.3  32.    6.8   0.  ]]
[15.8 94.  21.   0. ]
[34.  37.  18.7  0. ]
15.8
18.7
[15.8 31.5 30.4 ...  6.3 27.6 44.3]
5475
[21.  25.3  8.6 ... 23.7 12.5  4.6]
5475

In [36]:
# Row
print(weather[1])
# first 5th row
print(weather[:5])
print(weather[10:15])

[31.5  54.   25.3   3.71]
[[15.8  94.   21.    0.  ]
 [31.5  54.   25.3   3.71]
 [30.4  33.    8.6   3.14]
 [34.   37.   18.7   0.  ]
 [28.3  32.    6.8   0.  ]]
[[10.   65.   22.6   0.  ]
 [35.4  62.   11.1  15.56]
 [25.6  28.    8.9   0.  ]
 [19.1  62.   37.7   0.  ]
 [11.9  95.    5.4   2.2 ]]

In [ ]:
# Column Slicing
# every row but only temperature and Humidity
print(weather[:, 0:2])

# only wind and Precipitation
print(weather[:, 2:4])

# first 10 rows and first 2 column
print(weather[0:10, 0:2])

# first 5 rows and last 2 column
print(weather[:5, 2:])